### ISSUE TITLE
Cannot have space in Application Name when restarting docker container

### ISSUE THREAD

**Issue by Sil3ntLight** [morph1904/Tyger2#15]
When having a space in the Application Name and restarting docker, the docker container fails to start with an error about not being able to find a directory.
If the Application is named "My App", the container cannot find "App/My".

~~The only fix I've found so far is to `rm -r /var/lib/docker` then `apt remove --purge docker-compose docker.io && apt install docker-compose` and start from scratch.~~

I have yet to find a way to re-make the docker container without an entire machine reinstall.

**Comment by Sil3ntLight** [comment]
I found a fix:
Edit `/home/user/tyger2beta/data/caddyfile.conf`
Change the line `log /apps/Tyger2/data/<yourappname withspace>/<yourappname withspace>.log`
to replace `<yourappname withspace>` with the name of your app that shows up as a folder in `/home/user/tyger2beta/data/`.
Make sure to replace both the directory name and the log file to not have a space in it. 

Now you can re-run `docker-compose up` where the docker-compose.yml file is.

**Comment by morph1904** [comment]
Thanks for spotting this. This is an issue where the application is generating the logfile and directory names incorrectly. I will implement a fix for this soon and will update this when complete.

**Comment by bugs181** [comment]
Coming here from #23. 

> This has been fixed in the alpha branch, I just need to confirm that it works as expected.
Are you able to test using the Alpha branch to see if it fixes the issue?

How would we pull the Alpha branch using our docker compose files? Is the Alpha branch also posted to docker hub?

**Comment by morph1904** [comment]
This should do the trick:

```image: morph1904/tyger2:beta```

**Comment by morph1904** [comment]
@bugs181 - Did this work for you? If it did let me know and I will merge the branch and close this issue.

**Comment by bugs181** [comment]
> @bugs181 - Did this work for you? If it did let me know and I will merge the branch and close this issue.

Apologies for the delayed response. I hadn't gotten around to trying it until now. I can confirm that this fixed the issue! Great work.

**Comment by morph1904** [comment]
Fixed with merge #26 . Closing issue.
