### ISSUE TITLE
Feature Request: Custom certificates

### ISSUE THREAD

**Issue by goober2186** [morph1904/Tyger2#17]
I really like Tyger2 UI and how easy it is to manage, but I was just wondering if you would be able to add an option for specifying the certificates to use instead of pulling from lets encrypt automatically?

**Comment by morph1904** [comment]
We had this in a previous version, I will look into this and see how easy it would be to implement reliably.

**Comment by archness1** [comment]
+1 on this feature, especially with cloudflare origin certs.

**Comment by mosidevv** [comment]
Count me in for +1

**Comment by morph1904** [comment]
I am able to confirm that this feature is currently implemented in the new version of TygerCaddy (release TBC) and is undergoing testing.

**Comment by morph1904** [comment]
Closing issue as this feature is now in latest version.
