### ISSUE TITLE
Fresh install (not docker): ERR_CONNECTION_REFUSED after brief functionality

### ISSUE THREAD

**Issue by stevesanda** [morph1904/Tyger2#19]
Hello! I've just installed Tyger2 on a fresh install of Ubuntu 18.04.1 using the install.sh script. Things were working just fine - I was able to login and add some applications and addresses. Then, after adding a fifth application, the frontend simply stopped responding with "ERR_CONNECTION_REFUSED". I cannot log into the interface on port 9091, and when I access port 9090/install it mentions that an install is already active and that I need to move the db.sqlite file. I've tried this, and the front end still does not respond. Then, I completely removed the /apps/Tyger2/ directory and ran the install script again. I opened the install page in my browser, which worked, but the front end at port 9090 still isn't responding.

One thing I did notice in my subsequent attempts to run the install script was this error just before the end of the entire process:

`Requirement already satisfied: sqlparse>=0.2.2 in /usr/local/lib/python3.6/dist-packages (from Django>=2.2.4->-r /apps/Tyger2/newrequirements.txt (line 1))
The directory '/home/steve/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/steve/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: uwsgi in /usr/local/lib/python3.6/dist-packages
Starting TygerCaddy... Almost there!
Install complete! visit http://10.0.1.29 :9090/install in your chosen browser complete the install wizard.`

**Comment by stevesanda** [comment]
I've rebooted the machine and the frontend popped back up. I added some apps and addresses (new, since it's a fresh install) and hit "restart proxy". After that, I see red error on the frontend that says it cannot communicate with the back end.

**Comment by morph1904** [comment]
Hi, 

A connection refused error is usually caused by either the port not being open on the firewall or the service is not running. Please can you post the logs from the caddy and the uwsgi service here.

**Comment by morph1904** [comment]
Hi Stevesanda, 

Did you manage to resolve this issue?

**Comment by morph1904** [comment]
Closing as stale issue. Please feel free to re-open if you are still experiencing issues with Tyger,
