### ISSUE TITLE
nothing running on port 80

### ISSUE THREAD

**Issue by aporzio1** [morph1904/Tyger2#20]
Caddy service shows as starting on port 9091 and I can access the admin portal and add all of my applications but none of them actually work. When I run `netstat -l` i don't see anything running on port 80.

Am I missing something?

**Comment by morph1904** [comment]
Hi, there. 

Are you running on ubuntu or docker?

If running on ubuntu, please can you post the output of service caddy status?

**Comment by morph1904** [comment]
Hi aporzio1

Did you manage to resolve this issue?

**Comment by morph1904** [comment]
Hi as I've not heard back I will close this issue. Please feel free to reopen if you are still experiencing issues.
