### ISSUE TITLE
Spaces in app name crashes Tyger2/Caddy

### ISSUE THREAD

**Issue by bugs181** [morph1904/Tyger2#23]
I had an application with spaces in the name and this caused Tyger2 to not start. Both Caddy and Tyger2 became unresponsive.

**Comment by morph1904** [comment]
Hi Bugs, 

This is an active issue with #15 

This has been fixed in the alpha branch, I just need to confirm that it works as expected. 

Are you able to test using the Alpha branch to see if it fixes the issue?

**Comment by bugs181** [comment]
Closing as duplicate of #15. Apologies. I searched in the Github tracker but it did not show up anything for "spaces". Should have tried the singular "space" but Github search should be smarter than that.
