### ISSUE TITLE
Subfolder support or only subdomains supported?

### ISSUE THREAD

**Issue by ksurl** [morph1904/Tyger2#30]
After finally getting it up and running on docker, my 1st test was to put Jackett behind a proxy. It runs plain http on port 9117 in a container on the same docker host. Since there are no notes on what is the supported way to do it, I have been trying different things.

I added a new application with same docker host IP and port 9117, no websocket or transparent proxy enabled. Then I added a new address with a subdomain of a domain I own. It successfully got a LE cert. I can reach the page externally when I assign the app to it but it gives 421 error, site is not served on this interface. I tried adding a url link in the address settings but then it just fails to load anything from external but internally it points to the docker host IP so I go directly to the internal address (no more proxy?). 

Am I supposed to be doing 1 subdomain per application? I would prefer sub.domain.tld/app instead of app1.domain.tld, app2.domain.tld, etc.

**Comment by ksurl** [comment]
seems like it is assumign you will assign 1 subdomain per app. that's fine I guess. now I am running to a different issue. transmission and tautulli work fine since there is no path after the host:port url. plex and jackett have paths after the main domain such as plex:32400/web and jackett:9117/UI/Dashboard. I think that is what is breaking the proxy. it just fails to load anything. Is that what the url alias is for in the address section?

**Comment by ksurl** [comment]
Thanks, I will try the url proxy option and enable websocket/transparent options (does it ever hurt to do so if it is not needed?)

**Comment by morph1904** [comment]
Not really no. If the app does not use websockets, no data gets sent using the ws:// protocol, so no harm there. As for transparent, most consumer grade apps will require it. There are some apps that have some issues with it but they tend to be advanced. Not all apps are explicit about what header config they need, so if something doesn't work, just switch it off and see if it solves the issue. The change is instant, so not hard to try out.

**Comment by morph1904** [comment]
Here is the info if you ever need it:

transparent: Passes through host information from the original request as most backend apps would expect.
Shorthand for:
header_upstream Host {host}
header_upstream X-Real-IP {remote}
header_upstream X-Forwarded-For {remote}
header_upstream X-Forwarded-Proto {scheme}

**Comment by ksurl** [comment]
so the url proxy option works for transmission (setting Heimdall as the main landing page at root). I will have to play around with the other ones since they are not working out of the box. in this case, Jackett, Plex, Tautulli (tautulli did work as its own subdomain, but not as a url proxy under a subdomain)

**Comment by ksurl** [comment]
do you mind posting your urls for jacket and plex and tautulli? I've tried every combo of toggling the options and the url paths without any luck. direct connect locally works fine (IP:port).

**Comment by ksurl** [comment]
nevermind. I was able to get the rest up and running with individual subdomains. the only odd one out was plex, had to append web/index.html as a proxy url. and each one had their own cname dns record pointing to my ddns domain so I don't have to update them all, just the ddns IP.

**Comment by morph1904** [comment]
That is odd. My plex subdomain is an A record on cloudflare, I have plex set up as this:
![image](https://user-images.githubusercontent.com/3823307/94857729-dfcf3100-0429-11eb-90de-422735b765d3.png)

My subdomain is this:
![image](https://user-images.githubusercontent.com/3823307/94857813-fecdc300-0429-11eb-8574-6fe079f05d28.png)

This works fine for me. Be aware that you need to set the access address in some apps. In my Plex server settings have added the address as this:

![image](https://user-images.githubusercontent.com/3823307/94858030-52401100-042a-11eb-9b2d-a82ff82ed148.png)
