### ISSUE TITLE
New data directories created as root

### ISSUE THREAD

**Issue by mikeholownych** [morph1904/Tyger2#32]
Hello, 

First I wanted to say how much I like the product. After some manual intervention (caddy failed to download and install-- ended up manually building caddy) during the initial install, most things work quite well. Only issue that I have come across thus far is that when you add a new Address, the directory under /apps/Tyger2/data are created as u:root g:root; instead of u:www-data g:www-data (since caddy runs as www-data). Once I chown and chgrp the created directory and contents, everything works fine.

Running as ubuntu vm; installed on Ubuntu 20.04 fresh install.

**Comment by morph1904** [comment]
Closing as latest version is docker first.
