### ISSUE TITLE
Error! Please check your username and password and try again.

### ISSUE THREAD

**Issue by ljmellor** [morph1904/Tyger2#7]
I've tried several times now to get this up and running on my home lab server. I get through the install procedure very easily but cannot login afterwards despite having tried several different username/password combinations.

Running Debian Stretch with all the latest updates on a HP Proliant Gen8 Microserver.

**Comment by morph1904** [comment]
Hi there.

I do not know much about debian stretch but will try to help as much as possible. 

Few things first 

Have you visited the setup url and complete the form here ?

http://<ip-of-your-ubuntu-server>:9090/install

If you have for further information please can you ensure that uWSGI is running.

**Comment by ljmellor** [comment]
I've done the setup, I'll check uwsgi, I assume that runs as a systemd service

**Comment by morph1904** [comment]
Yes it is. 

Also please look for any more detailed error information in the developer console of either chrome or firefox. You should see the calls to the backend there and the responses.

**Comment by ljmellor** [comment]
I've checked and uwsgi is running with a status of "The Emperor is governing 1 vassals". Upon trying to login I'm getting the following error...
`
POST http://[my-local-ip]:9091/api/api-token-auth/ 502 (Bad Gateway)
`

**Comment by morph1904** [comment]
Ok. 

Please can you send a clean copy of the caddyfile.conf file and also ensure that caddy is running. 

Are you able to access the address http://[my-local-ip]:9091/api/ directly from the browser?

**Comment by ljmellor** [comment]
That url gives me the following...
`502 Bad Gateway`

Caddy is running, I also have apache2 installed but have tried stopping that then restarting caddy to no avail.

Here's the file contents...
`:9091/api { 
 	proxy / localhost:9090 { 
 		transparent 
 	} 
 } 
 :9091 { 
 	 root /apps/Tyger2/frontend/dist 
 	 log /apps/Tyger2/data/logs/frontend.log 
 	 rewrite { 
 		 regexp .* 
 		 to {path} / 
 	 } 
 }
`

Transmission was previously running on port 9091 (might be something worth considering a change to as transmission is a very commonly used service), I've moved that to port 9092 for now whilst I test this since changing ports in Tyger2 doesn't appear to be easily implemented just yet.

**Comment by morph1904** [comment]
Hi

The gui is running on port 9091 and the backend is running on 9090. There is a default setup to proxy requests on /api to port 9090. Are you able to access http://yourip:9090 ? If you are then the issue may be lying with caddy on port 80. Can you check that nothing other than caddy is running on port 80?

**Comment by ljmellor** [comment]
Sorry for the delay, I've rejigged my whole setup and gone with the docker installation which worked right off the bat. Was most likely a conflict between apache and caddy though I couldn't be certain. Thanks for the help and my apologies once more for any time I may have wasted.

**Comment by BlackF09** [comment]
I have the exact same issue but with the current docker beta image.
Any idea what is wrong with my setting? (Except of not internet accessible)


Within my Firefox I get a bunch of "cross-site access not allowed source:  https://fonts.gstatic.com..." and so no images at login screen. Trying to log in gets me only the _"XHR POST http://server.lab.domain.net:7071/api/api-token-auth/
[HTTP/1.1 502 Bad Gateway 28ms]"_

My portainer setting:
```
version: "2.4"                                                                                                          
services: 
  Tyger2Beta:
    image: morph1904/tyger2:beta
    container_name: tyger2beta
    volumes:
      - tyger2beta_data:/apps/Tyger2/data
      - tyger2beta_certs:/root/.caddy
    ports:
      - 443:443
      - 80:80
      - 7070:9090
      - 7071:9091
    restart: unless-stopped
```

Portainer log:
```
Operations to perform:,
  Apply all migrations: addresses, admin, apps, auth, contenttypes, dns, endpoints, install, sessions,
Running migrations:,
  No migrations to apply.,
  Your models have changes that are not yet reflected in a migration, and so won't be applied.,
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.,
Looks installed, doing nothing,
Creating uwsgi.log,
Creating uwsgi-access.log,
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Oct  9 01:34:40 2020] ***,
compiled with version: 9.3.0 on 01 October 2020 13:57:47,
os: Linux-4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17),
nodename: 440f96a69d03,
machine: x86_64,
clock source: unix,
detected number of CPU cores: 8,
current working directory: /,
detected binary path: /usr/local/bin/uwsgi,
!!! no internal routing support, rebuild with pcre support !!!,
uWSGI running as root, you can use --uid/--gid/--chroot options,
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** ,
*** WARNING: you are running uWSGI without its master process manager ***,
your memory page size is 4096 bytes,
detected max file descriptor number: 1048576,
*** starting uWSGI Emperor ***,
Starting ServicesActivating privacy features... done.,
,
Serving HTTP on port 9091 ,
http://:9091/api,
```

BTW: the logo is very similar to "Syncthing" is that on purpose?

**Comment by morph1904** [comment]
Hi There. 

This issue has been closed for a while now so I have created a new issue for you here:

#31
