### ISSUE TITLE
Net Cert Error

### ISSUE THREAD

**Issue by siddonj** [morph1904/Tyger2#9]
I am getting the below error when I connect to my proxied site.

![plex_image](https://user-images.githubusercontent.com/15673188/65434673-d2c63d80-dde4-11e9-9139-b8e321cf2fbf.png)
![Net_Cert_Message](https://user-images.githubusercontent.com/15673188/65434794-07d29000-dde5-11e9-8714-9194456647a0.png)

**Comment by morph1904** [comment]
Hello, 

It looks like you have chosen to use the HTTPs staging, This uses the LetsEncrypt test API and does not have rate limits, but does not generate a valid certificate. 

Please remove the HTTPs staging options from your addresses and restart the proxy. 

Morph

**Comment by morph1904** [comment]
Hi, 

Did this work for you? If it did please let me know, so that I can close this issue. 

Morph

**Comment by siddonj** [comment]
Sure did. Thanks

________________________________
